spring:
  application:
    name: rentx
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/rentx?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: ${MYSQL_PASSWD}
  redis:
    timeout: 3000

server:
  servlet:
    context-path: /${spring.application.name}
  port: 9988

logging:
  level:
    priv:
      thinkam:
        rentx:
          dao:
            mapper:
              UserMapper: debug

# Service version
rentx-web:
  service:
    version: 1.0.0

# Base packages to scan Dubbo Components (e.g @Service , @Reference)
dubbo:
  # Dubbo Config properties
  ## ApplicationConfig Bean
  application:
    id:  dubbo-consumer-demo
    name: dubbo-consumer-demo
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 12345