spring:
  application:
    name: rentx-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/rentx_admin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: ${MYSQL_PASSWD}
  redis:
    timeout: 3000

server:
  port: 9988

logging:
  level:
    priv:
      thinkam:
        rentx:
          admin:
            dao:
              mapper: debug

rentx:
  web:
    service:
      version: 1.0.0
      url: dubbo://localhost:12345

dubbo:
  application:
    name: dubbo-consumer-admin

mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*.xml