spring:
  application:
    name: rentx
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/rentx?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: ${MYSQL_PASSWD}
  redis:
    timeout: 3000

server:
  servlet:
    context-path: /${spring.application.name}
  port: 9988

logging:
  level:
    priv:
      thinkam:
        rentx:
          dao:
            mapper: debug

rentx:
  web:
    service:
      version: 1.0.0

dubbo:
  application:
    id:  dubbo-consumer-admin
    name: dubbo-consumer-admin
  protocol:
    id: dubbo
    name: dubbo
    port: 12345