spring:
  application:
    name: rentx-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/rentx?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: ${MYSQL_PASSWD}
  redis:
    timeout: 3000
    host: localhost
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
  security:
    ignore:
      paths: /plugins/**, /css/**, /js/**, /favicon.ico, /fonts/**, /img/**, /register, /forget, /captcha, /captcha/error

server:
  port: 9999

logging:
  level:
    priv:
      thinkam:
        rentx:
          web:
            dao:
              mapper: debug

rentx:
  web:
    service:
      version: 1.0.0

dubbo:
  scan:
    basePackages: priv.thinkam.rentx.web.service.impl
  application:
    name: dubbo-provider-web
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: N/A

mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*.xml
  global-config:
    db-config:
      id-type: auto

kaptcha:
  border: "yes"
  imageWidth: 100
  imageHeight: 45
  sessionKey: code
  textproducerCharLength: 4
  textproducerFontSize: 35
  textproducerFontColor: blue
  textproducerFontNames: 宋体,楷体,微软雅黑
